### ISSUE TITLE
Royalties

### ISSUE THREAD

**Issue by strokine** [noya-app/studio721#3]
I wanted to use studio721 Contract to create a Smart Contract for my NFT. But I must have royalties. It looks like there is no such option. Am I right? What could be done to add this feature?

**Comment by dabbott** [comment]
Hey! 721.so should support royalties. For marketplaces that support the royalties protocol:

![Studio_721_Contract](https://user-images.githubusercontent.com/1198882/153729986-1c8098cf-1cbb-41c3-b7c1-be995c518234.png)

For OpenSea you can set your royalties directly through their website. You can also do this via the `Contract URI` option, but that's a more advanced / less flexible option.

**Comment by strokine** [comment]
I see, thx for the info. I've checked the box, and IERC2981 was added with such implementation:
```
  function royaltyInfo(uint256, uint256 salePrice) external view override
    returns (address receiver, uint256 royaltyAmount)
  {
    return (address(this), (salePrice * 1000) / 10000);
  }
```
My assumption is that this is more like a suggestion, but it is not enforcing the royalty being sent to the token's creator.
If the platform decides to ignore it, it could.
Am I right? If not, how does it work?

**Comment by benmercerdev** [comment]
Yes, essentially the marketplace -- like Opensea or LooksRare -- can either support the royalty feature or not.
