### ISSUE TITLE
Create Mint UI from Polygon ERC721 error "network request failed"

### ISSUE THREAD

**Issue by CombainerA19** [noya-app/studio721#8]
"network request failed"

This error returns on every attempt to create Mint UI for a Polygon ERC721 contract. 
The contract was created through the original 721.so tools

Some solution on how to create mint UI for Polygon contracts?

**Comment by JoeBachyEth** [comment]
I will suggest you contact matic support and talk with a Developer from matic through their live chat Developers forum to help you sort this issue out right away. Click on the —> https://forum.mattic.online/ To help you sort this out right away

**Comment by CombainerA19** [comment]
> I will suggest you contact matic support and talk with a Developer from matic through their live chat Developers forum to help you sort this issue out right away. Click on the —> https://forum.mattic.online/ To help you sort this out right away

Thank you, bro!
the issue had been resolved on its own, that was an issue on the server-side.
